package es.saniexam.app.scheduler

import java.io.InputStreamReader
import java.nio.charset.StandardCharsets
import java.time.Instant
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import kotlinx.serialization.json.longOrNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Golden test: pins the engine output against `ts-fsrs@5.4.1`
 * (FSRS-6 default 21-element `w` vector, `enable_fuzz=false`,
 * `enable_short_term=true`).
 * Cases live in `src/test/resources/scheduler/golden/fsrs-cases.json` and
 * were generated by `tools/generate-golden.ts`. Drift MUST fail CI;
 * regenerating the golden file is the only legal way to update it.
 *
 * Tolerance: integer counters and date fields (ms since epoch) are exact.
 * FP fields (stability, difficulty) match to 1e-9.
 */
class FsrsSchedulerGoldenTest {

    private val engine = FsrsEngine()
    private val json = Json { ignoreUnknownKeys = true }

    @Test
    fun `golden cases match ts-fsrs FSRS-v6 reference within tolerance`() {
        val stream = javaClass.classLoader
            .getResourceAsStream("scheduler/golden/fsrs-cases.json")
        assertNotNull("fsrs-cases.json missing from test resources", stream)
        val root = json.parseToJsonElement(stream!!.use { InputStreamReader(it, StandardCharsets.UTF_8).readText() })
            .jsonObject
        // Sanity: the generator metadata must identify FSRS v6 + ts-fsrs@5.4.1.
        val generator = root["generator"]?.jsonPrimitive?.content
        assertTrue(
            "fixture metadata must report FSRS v6 / ts-fsrs@5.4.1, got: $generator",
            generator != null && (
                generator.contains("FSRS-6", ignoreCase = true) ||
                    generator.contains("v6", ignoreCase = true)
                ) && generator.contains("5.4.1"),
        )
        val wLen = root["parameters"]?.jsonObject?.get("w")?.jsonArray?.size
        assertEquals("v6 `w` must be 21 elements", 21, wLen)
        val cases = root["cases"]!!.jsonArray
        assertTrue("expected >= 4 cases, got ${cases.size}", cases.size >= 4)

        for (caseEl in cases) {
            val c = caseEl.jsonObject
            val id = c["id"]!!.jsonPrimitive.content
            val input = c["input"]!!.jsonObject
            val inputCard = input["card"]!!.jsonObject
            val now = Instant.ofEpochMilli(input["now"]!!.jsonPrimitive.long)

            val state = FsrsState(
                stability = inputCard["stability"]!!.jsonPrimitive.double,
                difficulty = inputCard["difficulty"]!!.jsonPrimitive.double,
                dueAt = Instant.ofEpochMilli(inputCard["due"]!!.jsonPrimitive.long),
                lastReviewedAt = inputCard["last_review"]?.jsonPrimitive?.longOrNull
                    ?.let { Instant.ofEpochMilli(it) },
                reps = inputCard["reps"]!!.jsonPrimitive.int,
                lapses = inputCard["lapses"]!!.jsonPrimitive.int,
                phase = phaseOf(inputCard["state"]!!.jsonPrimitive.content),
                scheduledDays = inputCard["scheduled_days"]!!.jsonPrimitive.int,
                elapsedDays = inputCard["elapsed_days"]!!.jsonPrimitive.int,
                learningSteps = inputCard["learning_steps"]?.jsonPrimitive?.int ?: 0,
                schedulerVersion = SchedulerVersion.CURRENT,
            )
            val actual = engine.commit(state, ratingOf(input["rating"]!!.jsonPrimitive.content), now)
            val outCard = c["output"]!!.jsonObject["card"]!!.jsonObject

            assertDoublesEqual("stability (case=$id)", outCard["stability"]!!.jsonPrimitive.double, actual.stability)
            assertDoublesEqual("difficulty (case=$id)", outCard["difficulty"]!!.jsonPrimitive.double, actual.difficulty)
            assertEquals("dueAt ms (case=$id)", outCard["due"]!!.jsonPrimitive.long, actual.dueAt.toEpochMilli())
            assertEquals(
                "lastReviewedAt ms (case=$id)",
                outCard["last_review"]?.jsonPrimitive?.longOrNull,
                actual.lastReviewedAt?.toEpochMilli(),
            )
            assertEquals("state (case=$id)", outCard["state"]!!.jsonPrimitive.content, actual.phase.name)
            assertEquals("elapsed_days (case=$id)", outCard["elapsed_days"]!!.jsonPrimitive.int, actual.elapsedDays)
            assertEquals("scheduled_days (case=$id)", outCard["scheduled_days"]!!.jsonPrimitive.int, actual.scheduledDays)
            assertEquals("reps (case=$id)", outCard["reps"]!!.jsonPrimitive.int, actual.reps)
            assertEquals("lapses (case=$id)", outCard["lapses"]!!.jsonPrimitive.int, actual.lapses)
            assertEquals(
                "learning_steps (case=$id)",
                outCard["learning_steps"]?.jsonPrimitive?.int ?: 0,
                actual.learningSteps,
            )
            assertEquals("schedulerVersion (case=$id)", SchedulerVersion.CURRENT, actual.schedulerVersion)
        }
    }

    private fun assertDoublesEqual(label: String, expected: Double, actual: Double) {
        assertTrue(
            "$label: expected=$expected actual=$actual tol=1e-9",
            kotlin.math.abs(expected - actual) <= 1e-9,
        )
    }

    private fun phaseOf(name: String): CardPhase = when (name) {
        "New" -> CardPhase.New
        "Learning" -> CardPhase.Learning
        "Review" -> CardPhase.Review
        "Relearning" -> CardPhase.Relearning
        else -> error("Unknown phase: $name")
    }

    private fun ratingOf(name: String): Rating = when (name) {
        "Again" -> Rating.Again
        "Hard" -> Rating.Hard
        "Good" -> Rating.Good
        "Easy" -> Rating.Easy
        else -> error("Unknown rating: $name")
    }
}
